services:
  php:
    build:
      context: docker/php
      args:
        PHP_VERSION: ${PHP_VERSION:-8.3}
    container_name: benzina-bundle-php
    volumes:
      - .:/app
      - ./docker/php/conf.d/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini:ro
